on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew buildProject --no-daemon
      - name: Copy Files
        run: sshpass -p ${{ secrets.PASSWORD }} scp -P ${{ secrets.PORT }} build/libs/core.jar build/libs/library.jar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/plugins